config/routes.rb
# Plugin's routes
resources :issue_reports_admin, :path => 'admin/issue_reports', :only => [:index]

app/controllers/issue_reports_admin_controller.rb
class IssueReportsAdminController < ApplicationController
  layout 'admin'
  menu_item :issue_reports_admin

  before_filter :require_admin

  helper :sort
  include SortHelper
  helper :users

  def index
    sort_init 'login', 'asc'
    sort_update %w(login firstname lastname mail receives_issue_reports)
    @limit = per_page_option

    @status = params[:status] || 1

    scope = User.logged.status(@status)
    scope = scope.like(params[:name]) if params[:name].present?
    scope = scope.in_group(params[:group_id]) if params[:group_id].present?

    @user_count = scope.count
    @user_pages = Paginator.new @user_count, @limit, params['page']
    @offset ||= @user_pages.offset
    @users =  scope.order(sort_clause).limit(@limit).offset(@offset).all

    respond_to do |format|
      format.html {
        @groups = Group.all.sort
        render :layout => !request.xhr?
      }
    end
  end
end

app/helpers/issue_reports_admin_helper.rb
module IssueReportsAdminHelper
  def issue_reports_admin_tabs
    tabs = [{:name => 'user_settings', :partial => 'issue_reports_admin/user_settings', :label => :label_issue_reports_user_settings}]
  end
end

app/views/issue_reports/_user_preferences.html.erb
<%= labelled_fields_for :pref, @user.pref do |pref_fields| %>
  <p><%= pref_fields.check_box :dont_receive_issue_reports %></p>
<% end %>

app/views/issue_reports_admin/_user_settings.html.erb
<p><%= l(:label_issue_reports_user_settings_description) %></p>

<%= form_tag(issue_reports_admin_index_path, :method => :get) do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>
<label for='status'><%= l(:field_status) %>:</label>
<%= select_tag 'status', users_status_options_for_select(@status), :class => "small", :onchange => "this.form.submit(); return false;"  %>

<% if @groups.present? %>
<label for='group_id'><%= l(:label_group) %>:</label>
<%= select_tag 'group_id', content_tag('option') + options_from_collection_for_select(@groups, :id, :name, params[:group_id].to_i), :onchange => "this.form.submit(); return false;"  %>
<% end %>

<label for='name'><%= l(:label_user) %>:</label>
<%= text_field_tag 'name', params[:name], :size => 30 %>
<%= submit_tag l(:button_apply), :class => "small", :name => nil %>
<%= link_to l(:button_clear), issue_reports_admin_index_path, :class => 'icon icon-reload' %>
</fieldset>
<% end %>
&nbsp;

<div class="autoscroll">
<table class="list">
  <thead><tr>
  <%= sort_header_tag('login', :caption => l(:field_login)) %>
  <%= sort_header_tag('firstname', :caption => l(:field_firstname)) %>
  <%= sort_header_tag('lastname', :caption => l(:field_lastname)) %>
  <%= sort_header_tag('receives_issue_reports', :caption => l(:field_receives_issue_reports), :default_order => 'desc') %>
  <%= sort_header_tag('mail', :caption => l(:field_mail)) %>
  </tr></thead>
  <tbody>
<% @users.each do |user| %>
  <tr class="<%= user.css_classes %> <%= cycle("odd", "even") %>">
  <td class="username"><%= avatar(user, :size => "14") %><%= link_to h(user.login), edit_user_path(user) %></td>
  <td class="firstname"><%= h(user.firstname) %></td>
  <td class="lastname"><%= h(user.lastname) %></td>
  <td class="tick"><%= (user.pref.dont_receive_issue_reports == '0') ? image_tag('true.png') : image_tag('false.png') %></td>
  <td class="email"><%= mail_to(h(user.mail)) %></td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<p class="pagination"><%= pagination_links_full @user_pages, @user_count %></p>

app/views/issue_reports_admin/index.html.erb
<% html_title(l(:label_issue_reports)) -%>
<h2><%= l(:label_issue_reports) %></h2>

<%= render_tabs issue_reports_admin_tabs %>